[package]
name = "histedit"
description = "Line editing, history and tokenization — a Rust re-implementation of libedit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
term.workspace = true
