[package]
name = "nshedit"
description = "Line editing, history and tokenization for nsh — a Rust re-implementation of libedit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
bsd = { workspace = true, optional = true }
bstr = { version = "1.13.0", default-features = false, features = ["std"] }
nshedit-plat.workspace = true
nshterm.workspace = true
postcard = { version = "1.1.3", default-features = false, features = ["use-std"] }
unicode-width = "0.2"

[features]
default = []
bsd = ["dep:bsd"]

[lints]
workspace = true
